package com.greenfoxacademy.vocseikatimasterwork.models.dtos.certificatesdtos;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.greenfoxacademy.vocseikatimasterwork.models.entities.Certificate;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.time.LocalDate;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@AllArgsConstructor
@NoArgsConstructor
@ApiModel(description = "Details of a certificate.")
public class CertificateDto {

  @ApiModelProperty(value = "Unique ID of the certificate, autogenerated by the database.")
  private Long id;

  @ApiModelProperty(value = "First name of the student.")
  private String studentFirstName;

  @ApiModelProperty(value = "Last name of the student.")
  private String studentLastName;

  @ApiModelProperty(value = "Start date of the course.")
  @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "yyyy-MM-dd")
  private LocalDate courseStartDate;

  @ApiModelProperty(value = "End date of the course.")
  @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "yyyy-MM-dd")
  private LocalDate courseEndDate;

  @ApiModelProperty(value = "The length of the course in hours.")
  private Integer courseDurationInHours;

  @ApiModelProperty(value = "Title of the course.")
  private String courseTitle;

  @ApiModelProperty(value = "Date of issue.")
  @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "yyyy-MM-dd")
  private LocalDate createdAt;

  public static CertificateDto convertToCertificateDto(Certificate certificate) {
    return new CertificateDto(certificate.getId(), certificate.getStudentFirstName(),
        certificate.getStudentLastName(), certificate.getCourseStartDate(),
        certificate.getCourseEndDate(), certificate.getCourseDurationInHours(),
        certificate.getCourseTitle(), certificate.getCreatedAt());
  }
}
